apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
spec:
  replicas: 1
  selector: {matchLabels: {app: notification-service}}
  template:
    metadata: {labels: {app: notification-service}}
    spec:
      containers:
        - name: notification-service
          image: your-dockerhub-user/notification-service:latest
          ports: [{containerPort: 8084}]
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/microservices
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
spec:
  selector: {app: notification-service}
  ports: [{port: 8084, targetPort: 8084}]
