spring.application.name=inventory-service
server.port=8083
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/microservices
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
